/DDSM115:
  ros__parameters:
    AW: 0.55
    WD: 0.13
    WO1: 0.44
    WO2: 0.0
    WO3: 0.46
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

/dynamixel_controller:
  ros__parameters:
    AW: 0.55
    WD: 0.13
    WO1: 0.44
    WO2: 0.0
    WO3: 0.46
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
